#include "lib_webgpu.h"
#include <assert.h>

extern "C" {

const char *wgpu_compilation_message_type_to_string(WGPU_COMPILATION_MESSAGE_TYPE type)
{
  return type == WGPU_COMPILATION_MESSAGE_TYPE_WARNING ? "warning"
        : (type == WGPU_COMPILATION_MESSAGE_TYPE_INFO ? "info" : "error");
}

int wgpu_vertex_format_channel_count(WGPU_VERTEX_FORMAT format)
{
  switch(format)
  {
  case WGPU_VERTEX_FORMAT_UINT8:
  case WGPU_VERTEX_FORMAT_SINT8:
  case WGPU_VERTEX_FORMAT_UNORM8:
  case WGPU_VERTEX_FORMAT_SNORM8:
  case WGPU_VERTEX_FORMAT_UINT16:
  case WGPU_VERTEX_FORMAT_SINT16:
  case WGPU_VERTEX_FORMAT_UNORM16:
  case WGPU_VERTEX_FORMAT_SNORM16:
  case WGPU_VERTEX_FORMAT_FLOAT16:
  case WGPU_VERTEX_FORMAT_FLOAT32:
  case WGPU_VERTEX_FORMAT_UINT32:
  case WGPU_VERTEX_FORMAT_SINT32:
    return 1;

  case WGPU_VERTEX_FORMAT_UINT8X2:
  case WGPU_VERTEX_FORMAT_SINT8X2:
  case WGPU_VERTEX_FORMAT_UNORM8X2:
  case WGPU_VERTEX_FORMAT_SNORM8X2:
  case WGPU_VERTEX_FORMAT_UINT16X2:
  case WGPU_VERTEX_FORMAT_SINT16X2:
  case WGPU_VERTEX_FORMAT_UNORM16X2:
  case WGPU_VERTEX_FORMAT_SNORM16X2:
  case WGPU_VERTEX_FORMAT_FLOAT16X2:
  case WGPU_VERTEX_FORMAT_FLOAT32X2:
  case WGPU_VERTEX_FORMAT_UINT32X2:
  case WGPU_VERTEX_FORMAT_SINT32X2:
    return 2;

  case WGPU_VERTEX_FORMAT_FLOAT32X3:
  case WGPU_VERTEX_FORMAT_UINT32X3:
  case WGPU_VERTEX_FORMAT_SINT32X3:
    return 3;

  case WGPU_VERTEX_FORMAT_UINT8X4:
  case WGPU_VERTEX_FORMAT_SINT8X4:
  case WGPU_VERTEX_FORMAT_UNORM8X4:
  case WGPU_VERTEX_FORMAT_SNORM8X4:
  case WGPU_VERTEX_FORMAT_UINT16X4:
  case WGPU_VERTEX_FORMAT_SINT16X4:
  case WGPU_VERTEX_FORMAT_UNORM16X4:
  case WGPU_VERTEX_FORMAT_SNORM16X4:
  case WGPU_VERTEX_FORMAT_FLOAT16X4:
  case WGPU_VERTEX_FORMAT_FLOAT32X4:
  case WGPU_VERTEX_FORMAT_UINT32X4:
  case WGPU_VERTEX_FORMAT_SINT32X4:
  case WGPU_VERTEX_FORMAT_UNORM10_10_10_2:
  case WGPU_VERTEX_FORMAT_UNORM8X4_BGRA:
    return 4;

  default:
    return 0;
  }
}

int wgpu_vertex_format_byte_size(WGPU_VERTEX_FORMAT format)
{
  switch(format)
  {
    case WGPU_VERTEX_FORMAT_UINT8:
    case WGPU_VERTEX_FORMAT_SINT8:
    case WGPU_VERTEX_FORMAT_UNORM8:
    case WGPU_VERTEX_FORMAT_SNORM8:
      return 1;

    case WGPU_VERTEX_FORMAT_UINT8X2:
    case WGPU_VERTEX_FORMAT_SINT8X2:
    case WGPU_VERTEX_FORMAT_UNORM8X2:
    case WGPU_VERTEX_FORMAT_SNORM8X2:
    case WGPU_VERTEX_FORMAT_UINT16:
    case WGPU_VERTEX_FORMAT_SINT16:
    case WGPU_VERTEX_FORMAT_UNORM16:
    case WGPU_VERTEX_FORMAT_SNORM16:
    case WGPU_VERTEX_FORMAT_FLOAT16:
      return 2;

    case WGPU_VERTEX_FORMAT_UINT8X4:
    case WGPU_VERTEX_FORMAT_SINT8X4:
    case WGPU_VERTEX_FORMAT_UNORM8X4:
    case WGPU_VERTEX_FORMAT_SNORM8X4:
    case WGPU_VERTEX_FORMAT_UINT16X2:
    case WGPU_VERTEX_FORMAT_SINT16X2:
    case WGPU_VERTEX_FORMAT_UNORM16X2:
    case WGPU_VERTEX_FORMAT_SNORM16X2:
    case WGPU_VERTEX_FORMAT_FLOAT16X2:
    case WGPU_VERTEX_FORMAT_FLOAT32:
    case WGPU_VERTEX_FORMAT_UINT32:
    case WGPU_VERTEX_FORMAT_SINT32:
    case WGPU_VERTEX_FORMAT_UNORM10_10_10_2:
    case WGPU_VERTEX_FORMAT_UNORM8X4_BGRA:
      return 4;

    case WGPU_VERTEX_FORMAT_UINT16X4:
    case WGPU_VERTEX_FORMAT_SINT16X4:
    case WGPU_VERTEX_FORMAT_UNORM16X4:
    case WGPU_VERTEX_FORMAT_SNORM16X4:
    case WGPU_VERTEX_FORMAT_FLOAT16X4:
    case WGPU_VERTEX_FORMAT_FLOAT32X2:
    case WGPU_VERTEX_FORMAT_UINT32X2:
    case WGPU_VERTEX_FORMAT_SINT32X2:
      return 8;

    case WGPU_VERTEX_FORMAT_FLOAT32X3:
    case WGPU_VERTEX_FORMAT_UINT32X3:
    case WGPU_VERTEX_FORMAT_SINT32X3:
      return 12;

    case WGPU_VERTEX_FORMAT_FLOAT32X4:
    case WGPU_VERTEX_FORMAT_UINT32X4:
    case WGPU_VERTEX_FORMAT_SINT32X4:
      return 16;

    default:
      return 0;
  }
}

const char *wgpu_vertex_format_to_string(WGPU_VERTEX_FORMAT format)
{
  switch(format)
  {
  case WGPU_VERTEX_FORMAT_INVALID: return "WGPU_VERTEX_FORMAT_INVALID";
  case WGPU_VERTEX_FORMAT_UINT8: return "WGPU_VERTEX_FORMAT_UINT8";
  case WGPU_VERTEX_FORMAT_UINT8X2: return "WGPU_VERTEX_FORMAT_UINT8X2";
  case WGPU_VERTEX_FORMAT_UINT8X4: return "WGPU_VERTEX_FORMAT_UINT8X4";
  case WGPU_VERTEX_FORMAT_SINT8: return "WGPU_VERTEX_FORMAT_SINT8";
  case WGPU_VERTEX_FORMAT_SINT8X2: return "WGPU_VERTEX_FORMAT_SINT8X2";
  case WGPU_VERTEX_FORMAT_SINT8X4: return "WGPU_VERTEX_FORMAT_SINT8X4";
  case WGPU_VERTEX_FORMAT_UNORM8: return "WGPU_VERTEX_FORMAT_UNORM8";
  case WGPU_VERTEX_FORMAT_UNORM8X2: return "WGPU_VERTEX_FORMAT_UNORM8X2";
  case WGPU_VERTEX_FORMAT_UNORM8X4: return "WGPU_VERTEX_FORMAT_UNORM8X4";
  case WGPU_VERTEX_FORMAT_SNORM8: return "WGPU_VERTEX_FORMAT_SNORM8";
  case WGPU_VERTEX_FORMAT_SNORM8X2: return "WGPU_VERTEX_FORMAT_SNORM8X2";
  case WGPU_VERTEX_FORMAT_SNORM8X4: return "WGPU_VERTEX_FORMAT_SNORM8X4";
  case WGPU_VERTEX_FORMAT_UINT16: return "WGPU_VERTEX_FORMAT_UINT16";
  case WGPU_VERTEX_FORMAT_UINT16X2: return "WGPU_VERTEX_FORMAT_UINT16X2";
  case WGPU_VERTEX_FORMAT_UINT16X4: return "WGPU_VERTEX_FORMAT_UINT16X4";
  case WGPU_VERTEX_FORMAT_SINT16: return "WGPU_VERTEX_FORMAT_SINT16";
  case WGPU_VERTEX_FORMAT_SINT16X2: return "WGPU_VERTEX_FORMAT_SINT16X2";
  case WGPU_VERTEX_FORMAT_SINT16X4: return "WGPU_VERTEX_FORMAT_SINT16X4";
  case WGPU_VERTEX_FORMAT_UNORM16: return "WGPU_VERTEX_FORMAT_UNORM16";
  case WGPU_VERTEX_FORMAT_UNORM16X2: return "WGPU_VERTEX_FORMAT_UNORM16X2";
  case WGPU_VERTEX_FORMAT_UNORM16X4: return "WGPU_VERTEX_FORMAT_UNORM16X4";
  case WGPU_VERTEX_FORMAT_SNORM16: return "WGPU_VERTEX_FORMAT_SNORM16";
  case WGPU_VERTEX_FORMAT_SNORM16X2: return "WGPU_VERTEX_FORMAT_SNORM16X2";
  case WGPU_VERTEX_FORMAT_SNORM16X4: return "WGPU_VERTEX_FORMAT_SNORM16X4";
  case WGPU_VERTEX_FORMAT_FLOAT16: return "WGPU_VERTEX_FORMAT_FLOAT16";
  case WGPU_VERTEX_FORMAT_FLOAT16X2: return "WGPU_VERTEX_FORMAT_FLOAT16X2";
  case WGPU_VERTEX_FORMAT_FLOAT16X4: return "WGPU_VERTEX_FORMAT_FLOAT16X4";
  case WGPU_VERTEX_FORMAT_FLOAT32: return "WGPU_VERTEX_FORMAT_FLOAT32";
  case WGPU_VERTEX_FORMAT_FLOAT32X2: return "WGPU_VERTEX_FORMAT_FLOAT32X2";
  case WGPU_VERTEX_FORMAT_FLOAT32X3: return "WGPU_VERTEX_FORMAT_FLOAT32X3";
  case WGPU_VERTEX_FORMAT_FLOAT32X4: return "WGPU_VERTEX_FORMAT_FLOAT32X4";
  case WGPU_VERTEX_FORMAT_UINT32: return "WGPU_VERTEX_FORMAT_UINT32";
  case WGPU_VERTEX_FORMAT_UINT32X2: return "WGPU_VERTEX_FORMAT_UINT32X2";
  case WGPU_VERTEX_FORMAT_UINT32X3: return "WGPU_VERTEX_FORMAT_UINT32X3";
  case WGPU_VERTEX_FORMAT_UINT32X4: return "WGPU_VERTEX_FORMAT_UINT32X4";
  case WGPU_VERTEX_FORMAT_SINT32: return "WGPU_VERTEX_FORMAT_SINT32";
  case WGPU_VERTEX_FORMAT_SINT32X2: return "WGPU_VERTEX_FORMAT_SINT32X2";
  case WGPU_VERTEX_FORMAT_SINT32X3: return "WGPU_VERTEX_FORMAT_SINT32X3";
  case WGPU_VERTEX_FORMAT_SINT32X4: return "WGPU_VERTEX_FORMAT_SINT32X4";
  case WGPU_VERTEX_FORMAT_UNORM10_10_10_2: return "WGPU_VERTEX_FORMAT_UNORM10_10_10_2";
  case WGPU_VERTEX_FORMAT_UNORM8X4_BGRA: return "WGPU_VERTEX_FORMAT_UNORM8X4_BGRA";
  default: return "<malformed WGPU_VERTEX_FORMAT value>";
  }
}

WGPU_WGSL_ELEMENT_TYPE wgpu_vertex_format_wgsl_element_type(WGPU_VERTEX_FORMAT format)
{
  switch(format)
  {
  case WGPU_VERTEX_FORMAT_UINT8:
  case WGPU_VERTEX_FORMAT_UINT8X2:
  case WGPU_VERTEX_FORMAT_UINT8X4:
  case WGPU_VERTEX_FORMAT_UINT16:
  case WGPU_VERTEX_FORMAT_UINT16X2:
  case WGPU_VERTEX_FORMAT_UINT16X4:
  case WGPU_VERTEX_FORMAT_UINT32:
  case WGPU_VERTEX_FORMAT_UINT32X2:
  case WGPU_VERTEX_FORMAT_UINT32X3:
  case WGPU_VERTEX_FORMAT_UINT32X4:
    return WGPU_WGSL_ELEMENT_TYPE_UINT;

  case WGPU_VERTEX_FORMAT_SINT8:
  case WGPU_VERTEX_FORMAT_SINT8X2:
  case WGPU_VERTEX_FORMAT_SINT8X4:
  case WGPU_VERTEX_FORMAT_SINT16:
  case WGPU_VERTEX_FORMAT_SINT16X2:
  case WGPU_VERTEX_FORMAT_SINT16X4:
  case WGPU_VERTEX_FORMAT_SINT32:
  case WGPU_VERTEX_FORMAT_SINT32X2:
  case WGPU_VERTEX_FORMAT_SINT32X3:
  case WGPU_VERTEX_FORMAT_SINT32X4:
    return WGPU_WGSL_ELEMENT_TYPE_SINT;

  case WGPU_VERTEX_FORMAT_FLOAT16:
  case WGPU_VERTEX_FORMAT_FLOAT16X2:
  case WGPU_VERTEX_FORMAT_FLOAT16X4:
    return WGPU_WGSL_ELEMENT_TYPE_HALF;

  default:
    assert(false && "Invalid WGPU_VERTEX_FORMAT passed to wgpu_vertex_format_wgsl_element_type()!");
    // Fall though to return a default float data type in release builds.
  case WGPU_VERTEX_FORMAT_UNORM8:
  case WGPU_VERTEX_FORMAT_UNORM8X2:
  case WGPU_VERTEX_FORMAT_UNORM8X4:
  case WGPU_VERTEX_FORMAT_UNORM16:
  case WGPU_VERTEX_FORMAT_UNORM16X2:
  case WGPU_VERTEX_FORMAT_UNORM16X4:
  case WGPU_VERTEX_FORMAT_UNORM10_10_10_2:
  case WGPU_VERTEX_FORMAT_UNORM8X4_BGRA:
  case WGPU_VERTEX_FORMAT_SNORM8:
  case WGPU_VERTEX_FORMAT_SNORM8X2:
  case WGPU_VERTEX_FORMAT_SNORM8X4:
  case WGPU_VERTEX_FORMAT_SNORM16:
  case WGPU_VERTEX_FORMAT_SNORM16X2:
  case WGPU_VERTEX_FORMAT_SNORM16X4:
  case WGPU_VERTEX_FORMAT_FLOAT32:
  case WGPU_VERTEX_FORMAT_FLOAT32X2:
  case WGPU_VERTEX_FORMAT_FLOAT32X3:
  case WGPU_VERTEX_FORMAT_FLOAT32X4:
    return WGPU_WGSL_ELEMENT_TYPE_FLOAT;
  }
}

} // ~extern "C"
